{{ config(
    materialized = 'table',
    schema = 'wencke'
) }}

SELECT

    wencke_id,
    artikel_nr,
    mandant,
    art_kurzname,
    art_artikelname,
    art_bezeichnung_2,
    art_bezeichnung_3,
    art_bezeichnung_4,
    art_warengruppe,
    art_warengruppe_alt,
    art_hauptkategorie_id,
    art_nebenkategorie_id,
    art_hauptkategorie_pim,
    art_nebenkategorie_pim,
    art_sektor,
    art_sortiment,
    art_abc_kategorie,
    art_sort_kz,
    art_ean_code,
    art_standard_ean,
    art_menge_ean_code,
    art_pzn,
    art_hilfsmittel_nr,
    art_herstellernummer,
    art_artikel_partner,
    adr_lieferant_1,
    adr_lieferant_2,
    adr_lieferant_3,
    adr_lieferant_4,
    adr_lieferant_5,
    art_ek_netto,
    art_vk_1,
    art_vk_2,
    art_vk_3,
    art_vk_4,
    art_vk_5,
    art_fap,
    art_skonto,
    art_ekst,
    art_rw,
    art_vk_alt_1,
    art_vk_alt_2,
    art_lagereinheit,
    art_artikelpreiseinheit,
    art_pflege_divisor,
    art_arzneimittel,
    art_medizinprodukt,
    art_mdr_produkt,
    art_apothekenpflichtig,
    art_gesperrter_artikel,
    art_auswahl_gesperrt,
    art_divers_flag,
    art_sammelartikel,
    art_nachhaltiger_artikel,
    art_nh_blauer_engel,
    art_nh_eu_ecolabel,
    art_nh_nordic_ecolabel,
    art_nh_fsc,
    art_created_at,
    art_geaendert_von,
    art_updated_at,
    source_hash

FROM {{ source('raw', 'wencke_lv_artikel_attribute') }}