version: 2

sources:
  - name: raw
    database: wenke
    schema: public   
    tables:
      - name: m36bel
      - name: m36pos
      - name: m36adrart
      - name: m36art
      - name: m36adr
      - name: m00id0202
      - name: m36nk
      - name: m36bg