version: 2

sources:
  - name: raw
    database: wenke
    schema: public

    tables:
      # M36

      - name: m36adr 
      - name: m36adrgrp
      - name: m36art
      - name: m36art_lgr
      - name: m36bel 
      - name: m36bg
      - name: m36fil
      - name: m36id0208
      - name: m36id0234
      - name: m36id0236
      - name: m36lag
      - name: m36nk
      - name: m36pos_test
      
      # M42
      - name: m42adr
      - name: m42adrgrp
      - name: m42art
      - name: m42art_lgr
      - name: m42bel
      - name: m42fil
      - name: m42lag
      - name: m42nk
    

      # M39
      - name: m39adr
      - name: m39adrgrp
      - name: m39art
      - name: m39art_lgr
      - name: m39bel
      - name: m39fil
      - name: m39lag
      - name: m39nk
      

      # M32
      - name: m32adr
      - name: m32adrgrp
      - name: m32art
      - name: m32art_lgr
      - name: m32bel
      - name: m32fil
      - name: m32lag
      - name: m32nk

      # Sonstige
      - name: m00id0202
      - name: tos_artikel_attribut

  - name: reporting
    database: wenke
    schema: reporting

    tables:
      - name: wencke_gold_pflichtkategorien
        description: "Wencke Pflichtkategorien"