version: 2

sources:
  - name: raw
    database: wenke
    schema: public

    tables:
      - name: m36bel
      - name: m36pos_old
      - name: m36adrgrp
      - name: m36art
      - name: m36adr
      - name: m00id0202
      - name: m36nk
      - name: m36bg
      - name: m42art
      - name: m39art
      - name: m32art
      - name: m36lag

  - name: reporting
    database: wenke
    schema: reporting

    tables:
      - name: wencke_gold_pflichtkategorien
        description: "Wencke Pflichtkategorien"